publish.yml: force push to gh-pages branch
Avoid force push errors:

  To https://github.com/virt-roles/virt-roles.github.io
   ! [rejected]        gh-pages -> gh-pages (fetch first)
  error: failed to push some refs to 'https://github.com/virt-roles/virt-roles.github.io'
  hint: Updates were rejected because the remote contains work that you do
  hint: not have locally. This is usually caused by another repository pushing
  hint: to the same ref. You may want to first integrate the remote changes
  hint: (e.g., 'git pull ...') before pushing again.
  hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Signed-off-by: Stefan Hajnoczi <stefanha@redhat.com>